version: '3'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - node-client
      - php-backend

  node-client:
    image: node:10.15
    working_dir: /var/app
    container_name: node-client
    volumes:
      - "./client:/var/app"
    expose:
      - "3000/tcp"
    environment:
      NODE_ENV: development
    entrypoint: "/var/app/bootstrap.sh"

  php-backend:
    build:
      context: ./docker/php
    container_name: php-backend
    volumes:
      - "./server:/var/app"
    expose:
      - "3000/tcp"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    command: "/var/app/bootstrap.sh"

